# Generated by Django 2.2.5 on 2019-10-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.IntegerField()),
                ('department', models.IntegerField()),
                ('credits', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('vacancies', models.SmallIntegerField()),
                ('shift', models.CharField(max_length=250)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('init_hout', models.TimeField()),
                ('final_hout', models.TimeField()),
                ('room', models.CharField(max_length=250)),
                ('discipline_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.DisciplineClass')),
            ],
        ),
        migrations.AddField(
            model_name='disciplineclass',
            name='teachers',
            field=models.ManyToManyField(through='offers.Alocation', to='offers.Professor'),
        ),
        migrations.AddField(
            model_name='alocation',
            name='discipline_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.DisciplineClass'),
        ),
        migrations.AddField(
            model_name='alocation',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Professor'),
        ),
    ]
